### ISSUE TITLE
报错了呢, 版本不兼容么

### ISSUE THREAD

**Issue by zhaokejin** [zhou-hao/hsweb4-examples#3]
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.r2dbc.h2.H2ConnectionFactory.getConnectionInfo(H2ConnectionFactory.java:154)

The following method did not exist:

    org.h2.engine.ConnectionInfo.<init>(Ljava/lang/String;Ljava/util/Properties;Ljava/lang/String;Ljava/lang/Object;)V

The method's class, org.h2.engine.ConnectionInfo, is available from the following locations:

    jar:file:/D:/Java/m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar!/org/h2/engine/ConnectionInfo.class

The class hierarchy was loaded from the following locations:

    org.h2.engine.ConnectionInfo: file:/D:/Java/m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.h2.engine.ConnectionInfo

Disconnected from the target VM, address: '127.0.0.1:54257', transport: 'socket'

有没有能跑起来的demo示例

**Comment by zhou-hao** [comment]
更新代码试试
