### ISSUE TITLE
访问doc.html报错，提示Knife4j文档请求异常

### ISSUE THREAD

**Issue by piglingcn** [zhou-hao/hsweb4-examples#4]
访问doc.html报错，提示Knife4j文档请求异常 http://127.0.0.1:8080/doc.html

**Comment by zhou-hao** [comment]
https://github.com/zhou-hao/hsweb4-examples/commit/7dbddb33a08e64f30690841d0e8119e92f24dc1a 已修复,更新最新代码试试。

**Comment by NaturalL** [comment]
hsweb4-webmvc-example 没修复，swagger-annotations版本冲突了，感觉webmvc没人用😂😂

**Comment by zhou-hao** [comment]
> hsweb4-webmvc-example 没修复，swagger-annotations版本冲突了，感觉webmvc没人用😂😂

hsweb的webmvc确实没人用，毕竟同类项目堆积如山....
